<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260119164751 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_event TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, event VARCHAR(255) NOT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BAE0AA7FCFA10B ON event (restaurant_id)');
        $this->addSql('CREATE TABLE historique_influence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_historique TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, holiday_name VARCHAR(255) DEFAULT NULL, is_holiday BOOLEAN DEFAULT NULL, is_school_vacations BOOLEAN DEFAULT NULL, vacation_name VARCHAR(255) DEFAULT NULL, weather_code INT DEFAULT NULL, tmax INT DEFAULT NULL, tmin INT DEFAULT NULL, prcd INT DEFAULT NULL, wspd INT DEFAULT NULL, day_of_week VARCHAR(255) DEFAULT NULL, is_weekend BOOLEAN DEFAULT NULL, influence INT DEFAULT NULL, pourcentage_occupation INT DEFAULT NULL, is_complet BOOLEAN DEFAULT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1B004F79FCFA10B ON historique_influence (restaurant_id)');
        $this->addSql('CREATE TABLE liste_typerestaurant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle_typerestaurant VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, notifiaction VARCHAR(255) NOT NULL, date_notification TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAFCFA10B ON notification (restaurant_id)');
        $this->addSql('CREATE TABLE restaurant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ville VARCHAR(255) DEFAULT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) NOT NULL, code_postal VARCHAR(255) NOT NULL, restaurant_user_id INT NOT NULL, type_restaurant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EB95123F6D258FE0 ON restaurant (restaurant_user_id)');
        $this->addSql('CREATE INDEX IDX_EB95123FC10AC75B ON restaurant (type_restaurant_id)');
        $this->addSql('CREATE TABLE restaurant_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, max_nb_couvert INT DEFAULT NULL, is_terrasse BOOLEAN DEFAULT NULL, restaurant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6FE56307B1E7706E ON restaurant_data (restaurant_id)');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7FCFA10B FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE historique_influence ADD CONSTRAINT FK_1B004F79FCFA10B FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAFCFA10B FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE restaurant ADD CONSTRAINT FK_EB95123F6D258FE0 FOREIGN KEY (restaurant_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE restaurant ADD CONSTRAINT FK_EB95123FC10AC75B FOREIGN KEY (type_restaurant_id) REFERENCES liste_typerestaurant (id)');
        $this->addSql('ALTER TABLE restaurant_data ADD CONSTRAINT FK_6FE56307B1E7706E FOREIGN KEY (restaurant_id) REFERENCES restaurant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD pseudo VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD nom_gerant VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD prenom_gerant VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD code_settings INT NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7FCFA10B');
        $this->addSql('ALTER TABLE historique_influence DROP CONSTRAINT FK_1B004F79FCFA10B');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAFCFA10B');
        $this->addSql('ALTER TABLE restaurant DROP CONSTRAINT FK_EB95123F6D258FE0');
        $this->addSql('ALTER TABLE restaurant DROP CONSTRAINT FK_EB95123FC10AC75B');
        $this->addSql('ALTER TABLE restaurant_data DROP CONSTRAINT FK_6FE56307B1E7706E');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE historique_influence');
        $this->addSql('DROP TABLE liste_typerestaurant');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE restaurant');
        $this->addSql('DROP TABLE restaurant_data');
        $this->addSql('ALTER TABLE "user" DROP pseudo');
        $this->addSql('ALTER TABLE "user" DROP nom_gerant');
        $this->addSql('ALTER TABLE "user" DROP prenom_gerant');
        $this->addSql('ALTER TABLE "user" DROP code_settings');
    }
}
