--
-- PostgreSQL database dump
--

\restrict BFIDceAdQlI26TF9nI1K06mxbw1fQrmAa3zJC7aiitWrhT4nT0wyHgchgQAkXx8

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 15.15 (Debian 15.15-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO admin;

--
-- Name: event; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.event (
    id integer NOT NULL,
    date_event timestamp(0) without time zone NOT NULL,
    event character varying(255) NOT NULL,
    restaurant_id integer NOT NULL
);


ALTER TABLE public.event OWNER TO admin;

--
-- Name: event_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: historique_affluence; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.historique_affluence (
    id integer NOT NULL,
    date_historique timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    holiday_name character varying(255) DEFAULT NULL::character varying,
    is_holiday boolean,
    is_school_vacations boolean,
    vacation_name character varying(255) DEFAULT NULL::character varying,
    weather_code integer,
    tmax integer,
    tmin integer,
    prcp double precision,
    wspd integer,
    day_of_week character varying(255) DEFAULT NULL::character varying,
    is_weekend boolean,
    affluence integer,
    occupancy_rate double precision,
    is_full boolean,
    restaurant_id integer NOT NULL
);


ALTER TABLE public.historique_affluence OWNER TO admin;

--
-- Name: historique_affluence_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.historique_affluence ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.historique_affluence_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);




--
-- Name: notification; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.notification (
    id integer NOT NULL,
    message character varying(255) NOT NULL,
    date_notification timestamp(0) without time zone NOT NULL,
    restaurant_id integer NOT NULL
);


ALTER TABLE public.notification OWNER TO admin;

--
-- Name: notification_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurant; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.restaurant (
    id integer NOT NULL,
    ville character varying(255) DEFAULT NULL::character varying,
    nom character varying(255) NOT NULL,
    adresse character varying(255) NOT NULL,
    code_postal character varying(255) NOT NULL,
    restaurant_user_id integer NOT NULL,
    type_restaurant character varying(255) DEFAULT NULL::character varying
);


ALTER TABLE public.restaurant OWNER TO admin;

--
-- Name: restaurant_data; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.restaurant_data (
    id integer NOT NULL,
    max_nb_couvert integer,
    is_terrasse boolean,
    restaurant_id integer NOT NULL
);


ALTER TABLE public.restaurant_data OWNER TO admin;

--
-- Name: restaurant_data_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.restaurant_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurant_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: restaurant_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.restaurant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.restaurant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    email character varying(180) NOT NULL,
    roles json NOT NULL,
    password character varying(255) NOT NULL,
    date_naissance timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    pseudo character varying(255) NOT NULL,
    nom_gerant character varying(255) NOT NULL,
    prenom_gerant character varying(255) NOT NULL,
    code_settings character varying(50) NOT NULL
);


ALTER TABLE public."user" OWNER TO admin;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: event event_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT event_pkey PRIMARY KEY (id);


--
-- Name: historique_affluence historique_affluence_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.historique_affluence
    ADD CONSTRAINT historique_affluence_pkey PRIMARY KEY (id);





--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);


--
-- Name: restaurant_data restaurant_data_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.restaurant_data
    ADD CONSTRAINT restaurant_data_pkey PRIMARY KEY (id);


--
-- Name: restaurant restaurant_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.restaurant
    ADD CONSTRAINT restaurant_pkey PRIMARY KEY (id);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);


--
-- Name: idx_1b004f79b1e7706e; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_1b004f79b1e7706e ON public.historique_affluence USING btree (restaurant_id);


--
-- Name: idx_3bae0aa7b1e7706e; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_3bae0aa7b1e7706e ON public.event USING btree (restaurant_id);


--
-- Name: idx_bf5476cab1e7706e; Type: INDEX; Schema: public; Owner: admin
--

CREATE INDEX idx_bf5476cab1e7706e ON public.notification USING btree (restaurant_id);


--
-- Name: uniq_6fe56307b1e7706e; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX uniq_6fe56307b1e7706e ON public.restaurant_data USING btree (restaurant_id);


--
-- Name: uniq_eb95123f6d258fe0; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX uniq_eb95123f6d258fe0 ON public.restaurant USING btree (restaurant_user_id);


--
-- Name: uniq_identifier_email; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX uniq_identifier_email ON public."user" USING btree (email);


--
-- Name: historique_affluence fk_1b004f79b1e7706e; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.historique_affluence
    ADD CONSTRAINT fk_1b004f79b1e7706e FOREIGN KEY (restaurant_id) REFERENCES public.restaurant(id);


--
-- Name: event fk_3bae0aa7b1e7706e; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.event
    ADD CONSTRAINT fk_3bae0aa7b1e7706e FOREIGN KEY (restaurant_id) REFERENCES public.restaurant(id);


--
-- Name: restaurant_data fk_6fe56307b1e7706e; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.restaurant_data
    ADD CONSTRAINT fk_6fe56307b1e7706e FOREIGN KEY (restaurant_id) REFERENCES public.restaurant(id);


--
-- Name: notification fk_bf5476cab1e7706e; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fk_bf5476cab1e7706e FOREIGN KEY (restaurant_id) REFERENCES public.restaurant(id);


--
-- Name: restaurant fk_eb95123f6d258fe0; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.restaurant
    ADD CONSTRAINT fk_eb95123f6d258fe0 FOREIGN KEY (restaurant_user_id) REFERENCES public."user"(id);


--
-- PostgreSQL database dump complete
--

\unrestrict BFIDceAdQlI26TF9nI1K06mxbw1fQrmAa3zJC7aiitWrhT4nT0wyHgchgQAkXx8

